### ISSUE TITLE
Wire frame 1(Admin-Web) 

### ISSUE THREAD

**Issue by jameriah30** [MerryFairyTalesAD440/UX-UI#1]

**Comment by jameriah30** [comment]
I am using both Balsamic and Adobe Xd, to create a Wire Frame for the Admin- Web app. So far I have spent 2 hours testing out both of these apps to see which one is a better fit. I estimate that it will take me 8 hours to complete this task.

**Comment by gshields5541** [comment]
I’m using XD too so it’s all good

Gerald

**Comment by jameriah30** [comment]
Update: I ended up using Lucid Charts as my wire framing tool. It took me 12 hours-ish total to complete, including meeting time with Melanie and Maria to discuss API and back end calls. It was difficult to coordinate a UI design with a corresponding API path structure since there are files in different languages. It got a bit confusing at times.
Attached is a PDF of the Wireframe:
[Wireframe1.pdf](https://github.com/MerryFairyTalesAD440/UX-UI/files/2785294/Wireframe1.pdf)

Also attached is a link to my wiki page:
https://github.com/MerryFairyTalesAD440/UX-UI/wiki/Admin-Web-Portal-Wireframe---Jeremiah-Smith
