### ISSUE TITLE
Upload File(Prototype--Drag and Drop/Browse):

### ISSUE THREAD

**Issue by jameriah30** [MerryFairyTalesAD440/UX-UI#13]

**Comment by gshields5541** [comment]
Working on the Drag and Drop code using Vue.js and AXIOS.js time: 3 hours

**Comment by gshields5541** [comment]
Working on the Drag and Drop code using Vue.js and AXIOS.js time: 10 hours

**Comment by gshields5541** [comment]
![screen shot 2019-02-03 at 6 35 01 pm](https://user-images.githubusercontent.com/20196881/52187474-88a33400-27e2-11e9-9f64-cd195e4c98fb.png)
![screen shot 2019-02-03 at 6 34 55 pm](https://user-images.githubusercontent.com/20196881/52187475-88a33400-27e2-11e9-8842-f3855d4174b0.png)
![screen shot 2019-02-03 at 6 34 47 pm](https://user-images.githubusercontent.com/20196881/52187476-88a33400-27e2-11e9-909f-84f756cf6a64.png)
![screen shot 2019-02-03 at 6 34 37 pm](https://user-images.githubusercontent.com/20196881/52187477-88a33400-27e2-11e9-9254-e86eeff0520a.png)

**Comment by jameriah30** [comment]
I'm not seeing your code on any branch to look at in order to do testing, so I created a bug. Please create a new branch with your code you have, so it can be tested.

**Comment by gshields5541** [comment]
I've completed the task: Total time 15 hours
