### ISSUE TITLE
A Script to obtain SAS token from storage: 

### ISSUE THREAD

**Issue by jameriah30** [MerryFairyTalesAD440/UX-UI#14]

**Comment by JLaveta** [comment]
Thought this might be relevant, just in case you haven't seen it: 

https://docs.microsoft.com/en-us/azure/storage/common/storage-dotnet-shared-access-signature-part-1

**Comment by gitsah** [comment]
Use Azure functions to generate and retrieve a key example: https://github.com/Azure-Samples/functions-node-sas-token

**Comment by gitsah** [comment]
Generate the token server-side: https://docs.microsoft.com/en-us/rest/api/eventhub/generate-sas-token

**Comment by gitsah** [comment]
I eventually found a way to make a C# script for this task. Every option I looked at seemed to require additional setup, this isn't much different. The App.config in the project needs to be configured for the account and container, though they could be hardcoded in as well, the account key was removed for security. The program.cs will print out the SAS key for the container to the console if the App.config is setup correctly.'

[SASKeyScript.zip](https://github.com/MerryFairyTalesAD440/UX-UI/files/2834494/SASKeyScript.zip)

In total it took me about 5 hours to complete this task.

**Comment by gitsah** [comment]
https://docs.microsoft.com/en-us/azure/storage/common/storage-powershell-guide-full
https://docs.microsoft.com/en-us/powershell/module/azure.storage/new-azurestorageblobsastoken?view=azurermps-6.13.0

potentially easier option, requires login instead of account key
