### ISSUE TITLE
Upload File API Call:

### ISSUE THREAD

**Issue by jameriah30** [MerryFairyTalesAD440/UX-UI#16]

**Comment by mtolrom** [comment]
About 5 hours estimated. Researching:
- build a simple VueJs app
- make API call with VueJs
- Upload file with VueJs
- Deploy VueJs app on Azure
- Fix post issues

**Comment by mtolrom** [comment]
Uploading a file with VueJs via an API call
Web API used : http://mekonecampusapi.azurewebsites.net/Help/Api/POST-api-Pictures
test page : http://cloudpracticumtest.azurewebsites.net/
uploaded image location : https://mekonecampusapistorage.blob.core.windows.net/campusimages/<your-image.name>
git page : https://github.com/mtolrom/VueJs-Api-Call-File-Upload
Testing : other fields are not required, upload files and plugin your files name in the image location url to verify that they have been uploaded.

**Comment by mtolrom** [comment]
I still need to fix the following issue to return meaningful response : 
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://10.0.0.155:8080/sockjs-node/info?t=1548737186079. (Reason: CORS request did not succeed).[Learn More]

**Comment by mtolrom** [comment]
Still working on image upload. I can get sas token but not upload image
Test page : http://cloudpracticumtest.azurewebsites.net/
Git : https://github.com/mtolrom/VueJs-Api-Call-File-Upload
Error : Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.Signature did not match. String to sign used

**Comment by mtolrom** [comment]
Code returning this now : "data": "", "status": 201, "statusText": "Created",

**Comment by mtolrom** [comment]
Images are being uploaded now, Mikal verified it.

**Comment by mtolrom** [comment]
code is here : https://github.com/MerryFairyTalesAD440/UX-UI/blob/MekoneUiUploadSasToken/merryfairytalesroot/root/VueJs-Api-Call-File-Upload/src/App.vue
app is here : http://cloudpracticumtest.azurewebsites.net/

**Comment by mtolrom** [comment]
Wiki: https://github.com/MerryFairyTalesAD440/UX-UI/wiki/7.-Authentication

**Comment by mtolrom** [comment]
API Resources used : 
GET SAS TOKEN : https://merryfairytales.azurewebsites.net/api/getSAS
UPLOAD IMAGE : https://ad440oneboxtempbb81.blob.core.windows.net/getsastoken/

**Comment by mtolrom** [comment]
completed along with routing between pages.
