### ISSUE TITLE
Wire frame 2(User-Kid-Mobile)

### ISSUE THREAD

**Issue by jameriah30** [MerryFairyTalesAD440/UX-UI#2]

**Comment by toddysm** [comment]
https://xd.adobe.com/view/aa512d06-f6ba-401f-4d90-aa4026fe6ee3-dc60/

**Comment by gshields5541** [comment]
This is some screenshots from the Wireframe Markup. To see a interactive version of the Wireframe markup, please visit https://xd.adobe.com/view/aa512d06-f6ba-401f-4d90-aa4026fe6ee3-dc60/ :

![screen shot 2019-01-22 at 7 31 01 pm](https://user-images.githubusercontent.com/20196881/51581314-66bdbf00-1e7c-11e9-925f-8b14ce231372.png)

![screen shot 2019-01-16 at 5 07 43 pm](https://user-images.githubusercontent.com/20196881/51288502-61123600-19b1-11e9-8cc1-08ac3b2906f1.png)

This is the main screen of Children's Book. When you click the card of the slide, it open the book.

![screen shot 2019-01-22 at 7 32 43 pm](https://user-images.githubusercontent.com/20196881/51581367-9c62a800-1e7c-11e9-9091-73032625c513.png)


![screen shot 2019-01-16 at 5 10 13 pm](https://user-images.githubusercontent.com/20196881/51288578-a7679500-19b1-11e9-8a5a-68ca4d1fe88d.png)

The story screen contains (1) A language pulldown menu (2) A sound toggle switch (3) A "Close" button (4) The appropriate storyboard (5) A play button that toggles the audio and (6) Forward [and Back in subsequent storyboards] buttons. If you select the language menu, a mockup menu will appear (but only for this storyboard). The Sound toggle button is workable (But only for the first storyboard). We need need the API to provide this functionality (Either via button functionality or via “touch/swipe” functionality)as well as match the appropriate storyboard with the audio (with the appropriate lanugage).

![screen shot 2019-01-16 at 5 11 30 pm](https://user-images.githubusercontent.com/20196881/51288614-d54cd980-19b1-11e9-9b22-f3d1cd245569.png)

This is the 2nd storyboard. This will have Forward and Back Buttons and a workable Close button.

![screen shot 2019-01-16 at 5 12 27 pm](https://user-images.githubusercontent.com/20196881/51288642-f7def280-19b1-11e9-937c-c65a7a725e3b.png)

This is the 3rd storyboard. This will have Forward and Back Buttons and a workable Close button.

![screen shot 2019-01-16 at 5 13 10 pm](https://user-images.githubusercontent.com/20196881/51288660-104f0d00-19b2-11e9-85fe-b09497d127d7.png)

This is the 4th storyboard. This will have Forward and Back Buttons and a workable Close button.

![screen shot 2019-01-16 at 5 14 00 pm](https://user-images.githubusercontent.com/20196881/51288682-34125300-19b2-11e9-8278-67b3b72506c7.png)

This is the 5th storyboard. This will have Forward and Back Buttons and a workable Close button.

![screen shot 2019-01-16 at 5 15 08 pm](https://user-images.githubusercontent.com/20196881/51288724-56a46c00-19b2-11e9-9599-80e2cfa61d34.png)

This is the 6th storyboard. This will have Forward and Back Buttons and a workable Close button.

![screen shot 2019-01-16 at 5 16 06 pm](https://user-images.githubusercontent.com/20196881/51288760-789dee80-19b2-11e9-8389-4e3e17f0ebf2.png)

This is the 7th storyboard. This will have Forward and Back Buttons and a workable Close button.

![screen shot 2019-01-16 at 5 16 48 pm](https://user-images.githubusercontent.com/20196881/51288784-91a69f80-19b2-11e9-8e00-3860149c6fa7.png)

This is the 8th storyboard. This will have Forward and Back Buttons and a workable Close button.

![screen shot 2019-01-16 at 5 17 32 pm](https://user-images.githubusercontent.com/20196881/51288809-abe07d80-19b2-11e9-8dd8-3e25a7a94515.png)

This is the 9th storyboard. This will have Forward and Back Buttons and a workable Close button.

![screen shot 2019-01-16 at 5 18 16 pm](https://user-images.githubusercontent.com/20196881/51288838-c3b80180-19b2-11e9-88cf-227578cdf917.png)

This is the 10th storyboard. This will have Forward and Back Buttons and a workable Close button.

![screen shot 2019-01-16 at 5 18 53 pm](https://user-images.githubusercontent.com/20196881/51288872-ddf1df80-19b2-11e9-9ae3-c4088b1108c5.png)

This is the 11th storyboard. This will have Forward and Back Buttons and a workable Close button.

![screen shot 2019-01-16 at 5 19 41 pm](https://user-images.githubusercontent.com/20196881/51288906-f7932700-19b2-11e9-97d6-bdbef1b9cf2c.png)

This is the 12th and last storyboard. This will have Forward and Back Buttons and a workable Close button.

![screen shot 2019-01-16 at 5 20 57 pm](https://user-images.githubusercontent.com/20196881/51288958-27dac580-19b3-11e9-935f-9c8f034f7d17.png)

This is the language menu. Click a language option to select a language. We would need the API to load the language text and audio file on the fly

![screen shot 2019-01-16 at 5 21 47 pm](https://user-images.githubusercontent.com/20196881/51288984-4640c100-19b3-11e9-88d6-128ee2c2fc3d.png)

This is the Spanish version of  the 1st Storyboard. Except for the language, the buttons are the same.

![screen shot 2019-01-16 at 5 22 48 pm](https://user-images.githubusercontent.com/20196881/51289002-66708000-19b3-11e9-8570-b9410c9ffe14.png)

This is the Japanese version of 1st Storyboard. Except for the language, which is presented in tategaki (Right to Left format), the buttons are the same. (This is a hypothetical markup which probably won't make the final code. I just did it just to see if it would support other languages like Asian Languages)

![screen shot 2019-01-16 at 5 25 17 pm](https://user-images.githubusercontent.com/20196881/51289090-c109dc00-19b3-11e9-9c30-b0a6c8ca0b34.png)

As I noted in a previous screen shot, the sound toggle switch is workable in the interactive markup I've posted:

![screen shot 2019-01-16 at 5 26 10 pm](https://user-images.githubusercontent.com/20196881/51289147-f7475b80-19b3-11e9-82cf-1894c20e8117.png)

![screen shot 2019-01-16 at 5 27 34 pm](https://user-images.githubusercontent.com/20196881/51289193-18a84780-19b4-11e9-898e-a07ff4940e87.png)

![screen shot 2019-01-22 at 7 33 57 pm](https://user-images.githubusercontent.com/20196881/51581405-c9af5600-1e7c-11e9-8475-2a429b87defa.png)

This is the main screen in a edit state. We should be able to click the trash can icon to toggle back to the regular state. To delete a book, just select the book.

![screen shot 2019-01-16 at 5 28 34 pm](https://user-images.githubusercontent.com/20196881/51289226-370e4300-19b4-11e9-82c1-39294ddbb7cd.png)
