### ISSUE TITLE
Add Page + Language Pages

### ISSUE THREAD

**Issue by jameriah30** [MerryFairyTalesAD440/UX-UI#23]

**Comment by HjLubas** [comment]
Create the 3 templates ( Book Page, Add Page, Add Languages)
Estimated:  2 - 4 hours
Code for each page
Estimated: 4 - 6 hours
Deploy to Storage account:
Estimated: 2 hours

Total Estimated Time:  8 - 12 hours

**Comment by HjLubas** [comment]
Wiki: https://github.com/MerryFairyTalesAD440/UX-UI/wiki/Vue-Add-Page-and-Add-Language-Page
Code: https://github.com/MerryFairyTalesAD440/UX-UI/tree/vueAddPage_Language/src
Demo: https://harryoneboxsprint2.z5.web.core.windows.net/
Pull Request:  https://github.com/MerryFairyTalesAD440/UX-UI/issues/55
Bug: https://github.com/MerryFairyTalesAD440/UX-UI/issues/55

Total time for completion:  4-6 hours

**Comment by mtolrom** [comment]
Completed along with routing.
