### ISSUE TITLE
Upload text file + calling the PUT API

### ISSUE THREAD

**Issue by jameriah30** [MerryFairyTalesAD440/UX-UI#24]

**Comment by mtolrom** [comment]
Direct upload image + sound + text files is working now. 
http://cloudpracticumtest.azurewebsites.net/
Will work on calling PUT next.

**Comment by mtolrom** [comment]
**Test page** : http://cloudpracticumtest.azurewebsites.net/
**Git code** : https://github.com/MerryFairyTalesAD440/UX-UI/blob/MekoneUiUploadSasToken/merryfairytalesroot/root/VueJs-Api-Call-File-Upload/src/App.vue
**PR** : https://github.com/MerryFairyTalesAD440/UX-UI/pull/42
**Wiki** : https://github.com/MerryFairyTalesAD440/UX-UI/wiki/8.-File-Upload---SAS-Token
**Container** : https://ad440oneboxtempbb81.blob.core.windows.net/getsastoken/
**Next work** : Move my code to the official folder structure.

**Comment by mtolrom** [comment]
Sign in is Sam's task.
