### ISSUE TITLE
Authentication with the API

### ISSUE THREAD

**Issue by jameriah30** [MerryFairyTalesAD440/UX-UI#27]

**Comment by SamRicha** [comment]
Estimated time for completion is 5 hours.

**Comment by SamRicha** [comment]
I added a button that only functioned when the user was logged into their Google account on the blob website. I still need to fix the CSS, and use the API.

Implementation: 1 hour
blob website: [link](https://oneboxtempstorage.blob.core.windows.net/$web/index.html)
Git commit: [link](https://github.com/MerryFairyTalesAD440/UX-UI/tree/9ec2b909592963b78c77408d7501ec64dbebd703)
Updated Wiki: [link](https://github.com/MerryFairyTalesAD440/UX-UI/wiki/Create-a-Login-Page)

**Comment by SamRicha** [comment]
Worked on integrating the login page to the UX-UI development branch, making the page with Vue JS, and researched Vue CLI.
Time Worked: 12 hours

**Comment by SamRicha** [comment]
Integrated a login page for the book website using Vue CLI.

Estimated Implementation: 5 hours
Total Implementation: 20 hours

Implementation Demo: [link](https://oneboxtempstorage.blob.core.windows.net/$web/index.html#)
Updated Wiki: [link](https://github.com/MerryFairyTalesAD440/UX-UI/wiki/Create-a-Login-Page)
Pull Request: [link](https://github.com/MerryFairyTalesAD440/UX-UI/pull/63)
Git Branch: [link](https://github.com/MerryFairyTalesAD440/UX-UI/tree/sambranch)
