### ISSUE TITLE
After Google account login no info displayed 

### ISSUE THREAD

**Issue by ncobb01** [MerryFairyTalesAD440/UX-UI#28]
https://oneboxtempstorage.blob.core.windows.net/$web/index.html#

I am able to select my Google account, however once I do nothing happens. No information is displayed, it just shows the login page again. The summary of the feature says it should be displaying my account info after entry. Thanks!

Using Windows, Firefox as browser. Expected to have custom user info shown, it was not, only stayed on the main page. 

Steps:
Go to azure feature location.
Click on 'sign in'
Select my Google account.
I am redirected to main page, with no custom login info.

**Comment by SamRicha** [comment]
Have you tried logging in without Adblock?

**Comment by ncobb01** [comment]
Issue is resolved, function working now as expected .
Appears to be due to an adblocker on my Firebox. Other browers including Internet Explorer functioned correctly.

**Comment by toddysm** [comment]
I tried with Firefox, Chrome, and Edge and none of the browsers show the user information. I see that the information is returned in the Developer Console but the page is not updated with it.

![image](https://user-images.githubusercontent.com/1007103/53827507-25ff9e00-3f30-11e9-81b4-801678f80abe.png)

**Comment by SamRicha** [comment]
@toddysm It should work now as long as you javascript is turned off. I was busy trying to change functionality for the next sprint but got stuck on another task and didn't update the page.
link: [https://oneboxtempstorage.blob.core.windows.net/$web/index.html](https://oneboxtempstorage.blob.core.windows.net/$web/index.html)
