### ISSUE TITLE
Investigate how to call API from browser using React

### ISSUE THREAD

**Issue by jameriah30** [MerryFairyTalesAD440/UX-UI#3]

**Comment by HjLubas** [comment]
Found that React JS works like an XML which consist of 3 life cycles:  Constructor where you call the constructor, parent class, and set the State - the data.  Then you go to the lifecycle  method where you fetch the data from the API and grab results and then set it to your state.  Then finally, render, where you show the State or data that you grab from the API.  This took me 3 - 4 hours to research.  Would still need to research further into other calls as well as different methods that we can use based on our app.  That should be another 3 - 5 hours hopefully.

**Comment by HjLubas** [comment]
Research further into security, cross-browser compatibility, and implement a simple code to run.  I used another API and rendered it to the web which wasn't too hard.   Took me probably about 4 to 5 hours.

**Comment by HjLubas** [comment]
![image](https://user-images.githubusercontent.com/34633828/51577524-ff4d4280-1e6e-11e9-9389-023ff92e6445.png)
![image](https://user-images.githubusercontent.com/34633828/51577560-1db33e00-1e6f-11e9-9d43-19fc1603f7d0.png)

Here are the images of the code and rendered site.  Could not load it on wiki.

**Comment by HjLubas** [comment]
Github Wiki: https://github.com/MerryFairyTalesAD440/UX-UI/wiki/API-Call-from-Browser-using-React

**Comment by HjLubas** [comment]
hosted web :  https://react-ercxp7.stackblitz.io/
