### ISSUE TITLE
Upload File(Prototype--Drag and Drop/Browse): --Create a branch with your working code for testing

### ISSUE THREAD

**Issue by jameriah30** [MerryFairyTalesAD440/UX-UI#34]

**Comment by jameriah30** [comment]
I'm not seeing your code on any branch to look at in order to do testing, so I created a bug. Please create a new branch with your code you have, so it can be tested.

**Comment by gshields5541** [comment]
Created vuedragdrop branch and commit to branch. Total time: 1 hour.
