### ISSUE TITLE
Investigate how to call API from browser using Angular

### ISSUE THREAD

**Issue by jameriah30** [MerryFairyTalesAD440/UX-UI#4]

**Comment by JLaveta** [comment]
Angular 6 has a service called "HttpClient" that can be used to make API calls. The module is imported using the following syntax (from Angular's Documentation):

```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { HttpClientModule } from '@angular/common/http';

@NGModule ({
    imports: [
        BrowserModule,
        // import HttpClientModule after BrowserModule
        HttpClientModule,
    ],
    declarations: [
        AppComponent,
    ],
    bootstrap: [ AppComponent ]
})
export class AppModule {}
```

From there, HttpClient can be injected into an application class as follows:

```
import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Injectable()
export class ConfigService {
  constructor(private http: HttpClient) { }
}
```
The HttpClient has all standard methods: post, get, put, and delete.

Angular also includes some tools for monitoring and logging the status of API calls, namely HttpRequest and HttpInterceptor. 

HttpRequest can be used to create a better user experience for our application by providing a status on the progress of file transfers. Users of this app will be downloading books along with a number of audio files, which may take some time depending on their connection. It might be nice to give users some feedback on that.

HttpInterceptor can be used to log when the request was sent, when a response was received, and the outcome of the call. These might be useful features for troubleshooting.

More details on the HttpClient can be found in Angular's documentation: https://angular.io/guide/http

**Comment by JLaveta** [comment]
Work so far: 1.5 hours.

**Comment by JLaveta** [comment]
Time estimate adjusted to account for additional work on getting an example webpage working with AngularJS API calls. Spent about an hour or so getting a working AngularJS index.html that calls an API GET. Still having some difficulty using Mikal's API, but will continue working on getting it going.

**Comment by JLaveta** [comment]
Got a basic API call working with AngularJS, here: https://codepen.io/anon/pen/GPaLRM?editors=1111

This took more time than expected as the API being used needed a slight configuration change. API calls were initially being rejected. It is functioning now. Spent around 2 hours trying to troubleshoot.

I am in the process of setting up quick site in Angular to demonstrate API calls.

**Comment by JLaveta** [comment]
2hrs45m - Finished a very basic example of the API call in Angular. I've got a locally hosted web page with a form for user name and a button. The app will call the API with data from the form and display the message received back from the API.

The next step is to work on updating the wiki page documenting this work.

**Comment by JLaveta** [comment]
Total about 7 hours.

Demo Link (temporary): https://angular-q3o3bc.stackblitz.io

GitHub Wiki: https://github.com/MerryFairyTalesAD440/UX-UI/wiki/API-Calls-Using-Angular

**Comment by JLaveta** [comment]
https://stackblitz.com/edit/angular-q3o3bc

TODO: Fix Git issues so code is properly added to repository.

**Comment by JLaveta** [comment]
Code has been properly added to GitHub. This required recreation of the Angular demo project to avoid a nested repository. 

GitHub branch link: https://github.com/MerryFairyTalesAD440/UX-UI/tree/angularDemo
