### ISSUE TITLE
Investigate how to call API from browser using Vue

### ISSUE THREAD

**Issue by jameriah30** [MerryFairyTalesAD440/UX-UI#5]

**Comment by ncobb01** [comment]
2 hours of research so far.

Good resource:
https://www.sitepoint.com/fetching-data-third-party-api-vue-axios/

**Comment by ncobb01** [comment]
Estimate: 6 hrs

**Comment by ncobb01** [comment]
6 hrs total work so far

**Comment by ncobb01** [comment]
7 hrs total time. Submitted working code to new GitHub branch
