### ISSUE TITLE
Demo - Deploy to azure storage blob

### ISSUE THREAD

**Issue by HjLubas** [MerryFairyTalesAD440/UX-UI#55]
It would be nice to see this deployed to a static website so we can take a look on how your code works for #13

**Comment by gshields5541** [comment]
I'm deploying the site, but it's not working once deployed. It's only working locally.

**Comment by HjLubas** [comment]
Did you do a run build and then deploy it to your blob?

**Comment by gshields5541** [comment]
Yes, I did.

Gerald

**Comment by gshields5541** [comment]
I’ll try it again through. It’s uploading right now to the blog

Gerald

**Comment by gshields5541** [comment]
The static website URL : https://webstorage1box.z5.web.core.windows.net <https://webstorage1box.z5.web.core.windows.net/>

**Comment by gshields5541** [comment]
Weirdly, it’s working, but the upload isn’t finished yet.

Gerald

**Comment by HjLubas** [comment]
Yup I see it. Cool. I'll test it out when I get to school. Thanks!

**Comment by gshields5541** [comment]
Did switching the Javascript off corrected the issue (Toddy said he switched off Javascript)?

Gerald

**Comment by HjLubas** [comment]
It's working so I'm not sure what you mean by javascript off.
