### ISSUE TITLE
Authentication-Communicate with Auth person from the API Team

### ISSUE THREAD

**Issue by jameriah30** [MerryFairyTalesAD440/UX-UI#6]
This task is assigned to Mekone as soon as he accepts his invitation to the Repo

**Comment by mtolrom** [comment]
So far, found 3 major methods for API authentication
1) HTTP Basic Auth : username/password in header, insecure if no SSL certificate
2) API Keys : fast, default approach, only authenticate, no specific authorization, insecure
3) OAuth : authentication + authorization, uses token, secure, recommended
I will check with the person in API Team in charge of Authentication what they want to do.

**Comment by mtolrom** [comment]
I also spoke with the API guy (@bigTimeBrad ) in charge of the authentication. He is still investigating.

**Comment by mtolrom** [comment]
Basic API : http://cloudpracticum.azurewebsites.net/
Swagger : http://cloudpracticum.azurewebsites.net/swagger/docs/v1
Developer portal : https://cloudpracticum.portal.azure-api.net/ (in progress)
I enabled OAuth 2.0 for the API but operations are not showing up. Will fix it and proceed with JWT policies.
Another web app to test the API : cloudpracticumtest.azurewebsites.net

**Comment by mtolrom** [comment]
You can make a call for one book using Id : http://cloudpracticum.azurewebsites.net/api/books/2
Or make a call for all books with no param : http://cloudpracticum.azurewebsites.net/api/book

**Comment by mtolrom** [comment]
I implemented and tested Web API with OAuth :
Web API with OAuth : http://cloudpracticum.azurewebsites.net/
Swagger UI : http://cloudpracticum.azurewebsites.net/swagger/ui/index
Swagger schema : http://cloudpracticum.azurewebsites.net/swagger/docs/v1
I abandoned the implementation with Azure API Management.

**Comment by mtolrom** [comment]
Wiki link : https://github.com/MerryFairyTalesAD440/UX-UI/wiki/7.-Authentication

**Comment by mtolrom** [comment]
5 hours of research and implementation.
