### ISSUE TITLE
BookDetails Page + Files Upload + Routing

### ISSUE THREAD

**Issue by jameriah30** [MerryFairyTalesAD440/UX-UI#68]

**Comment by mtolrom** [comment]
Book page completed along with routing.

**Comment by mtolrom** [comment]
Work completed this sprint #4:

01- add book with cover_image and redirect to book page
02- Go from BookList to 1 book page with details
03- Add picture and redirect to book page
04- add page and redirect to language page
05- add language and redirect to Text and Audio upload page
06- Add Text file and redirect to language page
07- Add audio file and redirect to language page
08- list pages
09- List languages

1- Code branch : https://github.com/MerryFairyTalesAD440/UX-UI/tree/MekoneForPR
2- Live test page : http://cloudpracticumtest.azurewebsites.net/BookList
3- PR merged : https://github.com/MerryFairyTalesAD440/UX-UI/pull/85
4- Bug open : I created a bug assigned to Melanie to fix duplicated book when editing but I can no longer find the bug. Maybe it was deleted.
5- Bug closed : https://github.com/MerryFairyTalesAD440/UX-UI/issues/19
6- Tracking hours : 20 hours
7- Wiki page : https://github.com/MerryFairyTalesAD440/UX-UI/wiki/8.-Files-Upload--SAS-Token---Routing

**Comment by mtolrom** [comment]
**Note : Uploading files is my specific task. The remaining is extra work.**
