### ISSUE TITLE
Investigate Hosting(HTML/JS/CSS/Images)

### ISSUE THREAD

**Issue by jameriah30** [MerryFairyTalesAD440/UX-UI#7]
This task is assigned to Sam as soon as he accepts his invitation to the Repo

**Comment by SamRicha** [comment]
I was looking into using GitHub Pages for hosting the project but one issue is that it happens to be a static site hosting service and doesn't support server-side code such as PHP, Ruby, or Python. Other than that I think it's a good service to use and it's free so if we are able to use it we could start implementing it right away without waiting for web host funding from the school. 

[https://help.github.com/articles/what-is-github-pages/](https://help.github.com/articles/what-is-github-pages/)

An alternative if we want dynamic web hosting can be Heroku. They provide fast app delivery, short cycles, and can run apps for free.

[https://www.heroku.com/developers](https://www.heroku.com/developers)

**Comment by SamRicha** [comment]
Azure Storage Hosting: [link](https://storagtestv0.blob.core.windows.net/$web/index.html)
Azure Web App Hosting: [link](http://testsite-v0.azurewebsites.net/)
