### ISSUE TITLE
Sign-in doesn't work for File Upload UI

### ISSUE THREAD

**Issue by toddysm** [MerryFairyTalesAD440/UX-UI#74]
Related to #24, I am getting the following issue when I try to sign in with Google at http://cloudpracticumtest.azurewebsites.net/

![image](https://user-images.githubusercontent.com/1007103/54094179-1e8b2b00-435c-11e9-8c25-282fba10c19d.png)

**Comment by mtolrom** [comment]
Sam is the owner of this page now and has fixed it by adding session.
