### ISSUE TITLE
Investigate how to call a restricted Blob from a browser

### ISSUE THREAD

**Issue by jameriah30** [MerryFairyTalesAD440/UX-UI#8]
This task is assigned to Sahand as soon as he accepts his invitation to the Repo

**Comment by gitsah** [comment]
I didn't do an estimate beforehand this time around since I forgot to at the beginning, but in the end it took me about 2 - 3 hours to research the topic and write the wiki page about it.

**Comment by gitsah** [comment]
Wiki page I completed: https://github.com/MerryFairyTalesAD440/UX-UI/wiki/Shared-Access-Signatures
