### ISSUE TITLE
 Create a login page(Sign in with…..)

### ISSUE THREAD

**Issue by jameriah30** [MerryFairyTalesAD440/UX-UI#9]

**Comment by SamRicha** [comment]
I estimate that it'll take 3 hours to complete this task.

**Comment by SamRicha** [comment]
Implementation took 9 hours.

Created a login page that utilizes Gmail as a way of logging in. As of right now when the user logs in they are shown their name, profile icon, and email.

Google Login Created: [https://webapplogin.azurewebsites.net/](https://webapplogin.azurewebsites.net/)

Updated UX/UI Wiki: [link](https://github.com/MerryFairyTalesAD440/UX-UI/wiki/4.-UX-UI-Research)

I still need to fix the CSS with the buttons and integrate the page with the other pages of the website.

**Comment by SamRicha** [comment]
Estimated time: 3 hours
Actual Implementation: 9.25 hours

Created a login page that utilizes Gmail as a way of logging in. As of right now when the user logs in they are shown their name, profile icon, and email.

Azure blob: [link](https://oneboxtempstorage.blob.core.windows.net/$web/index.html)
Wiki: [link](https://github.com/MerryFairyTalesAD440/UX-UI/wiki/Create-a-Login-Page)
Pull request: [link](https://github.com/MerryFairyTalesAD440/UX-UI/pull/18)
